CREATE TABLE IF NOT EXISTS USERS (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar NOT NULL,
  email varchar NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT email_is_one unique(email)
);

CREATE TABLE IF NOT EXISTS ITEMS (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar not null,
  description varchar not null,
  available boolean not null,
  owner BIGINT NOT NULL REFERENCES users(id),
  CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS BOOKING(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  start_date timestamp WITHOUT TIME ZONE NOT NULL,
  end_date timestamp WITHOUT TIME ZONE NOT NULL,
  itemId bigint references ITEMS (id),
  userId bigint references USERS (id),
  status varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMENTS(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  text varchar not null,
  itemId bigint references ITEMS (id),
  userId bigint references USERS (id)
);

CREATE TABLE IF NOT EXISTS REQUEST(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    description varchar NOT NULL

);

---DROP TABLE ITEMS;